Update tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,71 +1,140 @@
-# Common logic
-defaults: &defaults
-  steps:
-    - attach_workspace:
-        at: ~/
-    - run:
-        name: Replace Auth0 test credentials
-        command: |
-          mv $AUTH0_CFG.example $AUTH0_CFG
-          sed -i 's/YOUR_CLIENT_ID_HERE/'$AUTH0_TEST_CLIENT_ID'/g' $AUTH0_CFG
-          sed -i 's/your-tenant.auth0.com/'$AUTH0_TEST_DOMAIN'/g' $AUTH0_CFG
-          sed -i 's/YOUR_CLIENT_SECRET_HERE/'$AUTH0_TEST_CLIENT_SECRET'/g' $AUTH0_CFG
-    - run:
-        name: Build pull request
-        command: |
-          docker build -t $CIRCLE_JOB ./$SAMPLE_PATH
-          docker run -d -p 3000:3000 --name $CIRCLE_SHA1 --env-file $(pwd)/$AUTH0_CFG $CIRCLE_JOB
-        background: true
-    - run:
-        name: Wait for app to be available
-        command: |
-          sleep 50
-          docker run --network host --rm appropriate/curl --retry 8 --retry-connrefused -v localhost:3000
-    - run:
-        name: Run tests
-        command: |
-          docker create --network host --name tester codeception/codeceptjs codeceptjs run-multiple --all --steps
-          docker cp $(pwd)/lock_login_test.js tester:/tests/lock_login_test.js
-          docker cp $(pwd)/codecept.conf.js tester:/tests/codecept.conf.js
-          docker start -i tester
-        working_directory: scripts
-    - run:
-        name: Copy app container logs
-        command: |
-          mkdir -p /tmp/out
-          docker logs $CIRCLE_SHA1 > /tmp/out/app_logs.log
-          docker cp tester:/tests/out /tmp/
-        when: on_fail
-    - store_artifacts:
-        path: /tmp/out
+version: 2.1
 
-# Jobs and Workflows
-version: 2
+commands:
+  setup:
+    steps:
+      - run:
+          name: Configure environment
+          command: |
+            apk update
+
+      - checkout
+
+      - run:
+          name: Install dependencies
+          command: |
+            EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
+            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+            ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
+
+            if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then
+                >&2 echo 'ERROR: Invalid installer checksum'
+                rm composer-setup.php
+                exit 1
+            fi
+
+            php composer-setup.php --quiet
+            RESULT=$?
+            rm composer-setup.php
+
+            php composer.phar install --no-interaction --prefer-dist
+
+  setup-pcov:
+    steps:
+      - run:
+          name: Configure pcov
+          command: |
+            apk add autoconf gcc make musl-dev
+            pecl install pcov
+            docker-php-ext-enable pcov
+
+  run-phpinsights:
+    steps:
+      - run:
+          name: Run code quality analysis (PHP Insights)
+          command: php -d memory-limit=-1 ./vendor/bin/phpinsights -v --no-interaction --min-quality=100 --min-complexity=50 --min-architecture=100 --min-style=100
+
+  run-phpstan:
+    steps:
+      - run:
+          name: Run static code analysis (PHPStan)
+          command: php -d memory_limit=-1 ./vendor/bin/phpstan analyse --ansi
+
+  run-pest:
+    steps:
+      - run:
+          name: Run unit tests (Pest)
+          command: php -d memory_limit=-1 ./vendor/bin/pest --stop-on-failure --min=100
+
+  run-snyk:
+    steps:
+      - run:
+          name: Run vulnerabilities tests (Snyk)
+          command: |
+            apk add npm
+            npm install -g snyk
+            snyk test --dev --org=auth0-sdks --project-name=auth0-PHP
+
 jobs:
-  checkout:
-    machine: true
+  phpinsights:
+    parameters:
+      php:
+        type: string
+    docker:
+      - image: php:<< parameters.php >>-cli-alpine
+    steps:
+      - setup
+      - run-phpinsights
+  phpstan:
+    parameters:
+      php:
+        type: string
+    docker:
+      - image: php:<< parameters.php >>-cli-alpine
+    steps:
+      - setup
+      - run-phpstan
+  semgrep:
+    docker:
+      - image: returntocorp/semgrep:latest
     steps:
       - checkout
-      - run: git clone https://github.com/auth0-samples/spa-quickstarts-tests scripts
-      - persist_to_workspace:
-          root: ~/
-          paths:
-            - project
-            - scripts
-  01-login:
-    machine: true
-    environment:
-      - AUTH0_CFG: 01-Login/.env
-      - SAMPLE_PATH: 01-Login
-    <<: *defaults
+      - run:
+          name: Run static code analysis (Semgrep)
+          command: semgrep --config auto
+  pest:
+    parameters:
+      php:
+        type: string
+    docker:
+      - image: php:<< parameters.php >>-cli-alpine
+    steps:
+      - setup
+      - setup-pcov
+      - run-pest
+  snyk:
+    parameters:
+      php:
+        type: string
+    docker:
+      - image: php:<< parameters.php >>-cli-alpine
+    steps:
+      - setup
+      - run-snyk
 
 workflows:
-  version: 2
-  quickstarts_login:
+  test:
     jobs:
-      - checkout:
-          context: Quickstart Web App Test
-      - 01-login:
-          context: Quickstart Web App Test
+      - semgrep
+      - phpinsights:
+          matrix:
+            parameters:
+              php: ["8.0", "8.1"]
+      - phpstan:
+          matrix:
+            parameters:
+              php: ["8.0", "8.1"]
+      - pest:
+          matrix:
+            parameters:
+              php: ["8.0", "8.1"]
+      - hold:
+          type: approval
+      - snyk:
+          matrix:
+            parameters:
+              php: ["8.0", "8.1"]
+          context:
+            - snyk-env
           requires:
-            - checkout
+            - hold
